services:
  - type: web
    name: fourpaws-backend
    env: node
    plan: free
    buildCommand: cd FourPaws/backend && npm install
    startCommand: cd FourPaws/backend && npm start
    envVars:
      - fromGroup: env
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 7d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
  - type: static
    name: fourpaws-frontend
    env: static
    buildCommand: cd FourPaws/frontend && npm install && npm run build
    publishPath: FourPaws/frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_IMGBB_API_KEY
        sync: false
      - key: VITE_Payment_Gateway_PK
        sync: false
